from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# !!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = False

## Find Cointegrated Pairs
FIND_COINTEGRATED = True

# Place Trades
PLACES_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1800

# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

# KEYS - Production
# Must to be on Mainnet on DYDX
ETHEREUM_ADDRESS_MAINNET = config("ETHEREUM_ADDRESS_MAINNET")
ETH_PRIVATE_KEY_MAINNET = config("ETH_PRIVATE_KEY_MAINNET")
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")
HTTP_PROVIDER_MAINNET = config("HTTP_PROVIDER_MAINNET")

# KEYS - Development
# Must to be on Testnet on DYDX
ETHEREUM_ADDRESS_TESTNET = config("ETHEREUM_ADDRESS_TESTNET")
ETH_PRIVATE_KEY_TESTNET = config("ETH_PRIVATE_KEY_TESTNET")
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")
HTTP_PROVIDER_TESTNET = config("HTTP_PROVIDER_TESTNET")

# KEYS - Export
ETHEREUM_ADDRESS = ETHEREUM_ADDRESS_MAINNET if MODE == "PRODUCTION" else ETHEREUM_ADDRESS_TESTNET
ETH_PRIVATE_KEY = ETH_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else ETH_PRIVATE_KEY_TESTNET
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI
